### ISSUE TITLE
Universal Properties

### ISSUE THREAD

**Issue by cyouh95** [Justzergit/prj-rev-bwfs-dasmoto#4]
Alternatively, for universal properties such as the font, you could use the entire `body` element as the selector instead of listing out each element.

```css
body {
  font-family: "Helvetica", sans-serif;
}
```

https://github.com/Justzergit/prj-rev-bwfs-dasmoto/blob/master/Dasmoto's%20Arts%20%26%20Crafts/resources/style.css#L1
